# Generated by Django 5.2 on 2025-05-09 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_color_alter_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(choices=[('128', 128), ('256', 256), ('512', 512)], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 12, 14, 57, 863360)),
        ),
    ]
