# Generated by Django 5.2 on 2025-05-09 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_color_product_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 9, 12, 16, 5, 675954)),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(choices=[('128gb', 128), ('256gb', 256), ('512gb', 512)], default=1, max_length=10),
        ),
    ]
